-- INSERT INTO dbo.AgcmTable (AGPO, AGITEM, AGPART, AGRUN, AGPMCOMMENTS, AGCPEXP) 
-- VALUES
-- ('623000090570', 1, '312T3011-101', 12, 'BURNDOWN', 'N');

-- UPDATE dbo.AgcmTable SET AGPMCOMMENTS = 'BURNDOWN' 
-- WHERE AGPO = '623000090570'
-- AND AGITEM = 1
-- AND AGRUN =  12
-- ;

-- select top 10 * from AgwoTable;

-- select top 10 * from dbo.QueueInfo; 

-- SELECT * FROM AgcmTable WHERE AGPO = '613000529984';


-- DELETE FROM dbo.AgcmTable WHERE AGPO='613000524555' AND AGRUN=10;

SELECT COUNT(OPREF) AS GOAL FROM dbo.RnopTable 
    WHERE OPCENTER = '1600'
    AND OPCOMPLETE = 1 AND OPCOMPDATE > CAST(GETDATE() as DATETIME) - 21 AND OPCOMPDATE < CAST(GETDATE() AS DATETIME) - 20;
    -- AND OPSCHEDDATE <= CAST(GETDATE() as DATETIME) AND OPCOMPLETE = 0;
 

-- SELECT rt.RUNREF, rt.RUNNO, rt.RUNCOMPLETE, rt.RUNQTY, rt.RUNOPCUR, rt.RUNPRIORITY, rt.RUNRTNUM, rnop.OPCENTER, rnop.OPCOMPDATE, rnop.OPINSP
-- FROM dbo.RunsTable as rt
-- LEFT JOIN dbo.RnopTable AS rnop ON rt.RUNREF = rnop.OPREF AND rt.RUNNO = rnop.OPRUN
-- ORDER BY ;



